os: linux
dist: xenial
language: node_js
node_js:
  - node
  - 'lts/*'
after_script:
  - cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - stage: lint
      node_js:
        - node
      script:
        - "yarn lint --no-fix"
    - stage: deploy
      node_js:
        - node
      script:
        - yarn docs:build
      deploy:
        edge: true
        provider: pages
        strategy: git
        cleanup: false
        local_dir: docs/.vuepress/dist
        token: $GITHUB_TOKEN
        keep_history: true

stages:
  - lint
  - test
  - name: deploy
    if: branch = master
